version: '2'
services:
  spark-master:
    image: ${USERNAME}/spark-master:${TAG}
    container_name: spark-master
    ports:
      - "8083:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
    networks:
      - spark-net

  spark-worker-1:
    image: ${USERNAME}/spark-worker:${TAG}
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8093:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
    networks:
      - spark-net

networks:
  spark-net:
    external:
      name: spark-net
