ARG USERNAME
ARG TAG

FROM $USERNAME/spark-submit:$TAG

LABEL maintainer="Gezim Sejdiu <g.sejdiu@gmail.com>, Giannis Mouchakis <gmouchakis@gmail.com>"

ENV SPARK_APPLICATION_JAR_NAME application-1.0

COPY template.sh /

#RUN apk add --no-cache openjdk11 maven\
#      && chmod +x /template.sh \
#      && mkdir -p /app \
#      && mkdir -p /usr/src/app

RUN apt-get install -y \
      openjdk-11-jdk maven

RUN chmod +x /template.sh \
      && mkdir -p /app \
      && mkdir -p /usr/src/app

# Copy the POM-file first, for separate dependency resolving and downloading
ONBUILD COPY pom.xml /usr/src/app
ONBUILD RUN cd /usr/src/app \
      && mvn dependency:resolve
ONBUILD RUN cd /usr/src/app \
      && mvn verify

# Copy the source code and build the application
ONBUILD COPY . /usr/src/app
ONBUILD RUN cd /usr/src/app \
      && mvn clean package

CMD ["/bin/bash", "/template.sh"]
